name: test

on: [push]

jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
           test_secret = ${{ secrets.TestSecret }}
        run: |
          echo $test_secret
