name: test

on: [push]

jobs:
  show_secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
           test_secret : ${{ secrets.TestSecret }}
           test_secret2: ${{ secrets.TEST_SECRET }}
        run: |
          echo "$test_secret"  "$test_secret2"
